/* getting all the name of triggers */
SELECT Concat('DROP TRIGGER ', Trigger_Name, ';') FROM  information_schema.TRIGGERS WHERE TRIGGER_SCHEMA = 'assetmgt';

DROP TRIGGER AFTER_ASSET_ALLOCATION;
DROP TRIGGER AFTER_ASSET_DEALLOCATION;
DROP TRIGGER AFTER_ADDING_STORAGE;
DROP TRIGGER AFTER_ASSET_CREATION;
DROP TRIGGER AFTER_ASSET_STATUS_CHANGED;
DROP TRIGGER AFTER_ASSET_UPDATE;
DROP TRIGGER AFTER_REMOVE_STORAGE;
DROP TRIGGER BEFORE_ASSET_DELETE;
DROP TRIGGER AFTER_TICKET_RAISED;
DROP TRIGGER AFTER_TICKET_SOLVED;